"""empty message

Revision ID: 92ebfda2ea6b
Revises: 
Create Date: 2023-02-14 11:33:41.798783

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "92ebfda2ea6b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "role",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Unicode(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    op.create_table(
        "imports",
        sa.Column("id_import", sa.Integer(), nullable=False),
        sa.Column("file_name", sa.Unicode(), nullable=True),
        sa.Column(
            "date_import", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("email", sa.Unicode(), nullable=True),
        sa.Column("id_prc", sa.Integer(), nullable=True),
        sa.Column("nb_row_total", sa.Integer(), nullable=True),
        sa.Column("nb_row_inserted", sa.Integer(), nullable=True),
        sa.Column("error_file", sa.Unicode(), nullable=True),
        sa.Column("delimiter", sa.Unicode(), nullable=True),
        sa.Column("service", sa.Unicode(), nullable=False),
        sa.Column("timezone", sa.Unicode(), nullable=True),
        sa.PrimaryKeyConstraint("id_import"),
        schema="public",
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_uuid", postgresql.UUID(), nullable=False),
        sa.Column("firstname", sa.Unicode(), nullable=True),
        sa.Column("surname", sa.Unicode(), nullable=True),
        sa.Column("login", sa.Unicode(), nullable=True),
        sa.Column("pwd", sa.String(length=300), nullable=True),
        sa.Column("email", sa.Unicode(), nullable=False),
        sa.Column("id_role", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id_role"],
            ["public.role.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user", schema="public")
    op.drop_table("imports", schema="public")
    op.drop_table("role", schema="public")
    # ### end Alembic commands ###
