"""empty message

Revision ID: ec081d1930de
Revises: 9ae34f209f4a
Create Date: 2022-10-06 13:01:35.985994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec081d1930de'
down_revision = '9ae34f209f4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('imports', sa.Column('service', sa.Unicode(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('imports', 'service')
    # ### end Alembic commands ###
